### ISSUE TITLE
How to use the GAN model [21] PPNG in your paper?

### ISSUE THREAD

**Issue by xkx0430** [penincillin/DREAM#11]
Could you share your method to demonstrate the visualization of deep features?
It's very interesting. Thanks.

**Comment by penincillin** [comment]
This part is implemented by my partner and I am not very familiar with  the details. I have discussed with him but he is busy with another deadline recent days so I couldn't give a concrete answer right now. I will have another discussion with him before this weekend and after that I will give you a detailed answer . Thanks~

**Comment by xkx0430** [comment]
Thank you very much! The GAN's part in your paper is very exiting!!! Expecting...

**Comment by VeronikaVasilyeva** [comment]
yes, it's very  interesting thing. I too expect

**Comment by penincillin** [comment]
Sorry for my delayed reply, here is the answer after I disscussed with my partner.
We used the version Noiseless joint PPGN-h proposed in the paper specifically. We replace the Encoder Network with an End2End trained model and then we get a Generator Network which is able to decode a image given a vector of feature. And it could help to visualize the mapped feature as well

**Comment by xkx0430** [comment]
Thank you. And I want to know whether the Noiseless joint PPGN-h is retrained with MS-Celeb-1M or some other dataset.

**Comment by penincillin** [comment]
Yes, it is trained on cleaned Celeb-1M

**Comment by tjusxh** [comment]
If could you share the model about reconstruction? That would be appreciated it.
