### ISSUE TITLE
Hi, there is something wrong with my understand? TKS

### ISSUE THREAD

**Issue by xiaoxingzeng** [penincillin/DREAM#13]
In your paper , the ResNet18 training in Naive method with MS-Celeb-1M achieve 8.40.
But when test CFP dataset with your released model, The result is 4.85.
![qq 20180609231434](https://user-images.githubusercontent.com/22523429/41193178-844656ca-6c3b-11e8-9e6b-206c4eee085c.jpg)

So there is something wrong when I understand your paper?

**Comment by penincillin** [comment]
Actually, the resnet18 model you use is the model trained for IJBA. This model was trianed with full MS-Celeb-1M and may contain the same celebrities as CFP dataset.
The model trained for CFP dataset was trained with a subset of MS-Celeb-1M in which the celebrities in CFP dataset has been excluded. 
cfp_res50_naive.pth.tar and cfp_res50_end2end.pth.tar are models for CFP dataset.

**Comment by xiaoxingzeng** [comment]
The Ms-Celeb-1M dataset in your paper is cleaned againg by you or sensetime?
