### ISSUE TITLE
Have you ever tried on image with different pitch?

### ISSUE THREAD

**Issue by inkzk** [penincillin/DREAM#14]
I have been training DREAM on  different pitch angle images for a long time, and it still seems not a feasible work.
Have you ever tried on pitch angles?

**Comment by penincillin** [comment]
The same question you asked was also quest by one of reviewers. We believe our simple idea can also work on the pitch issue. However, the most pivot problem is the dataset. The yaw distribution on MS-Celeb-1M and the propose of CFP benchmark allow us to conduct a relatively solid experiment. If you wish to experiment on the pitch, you may build your benchmark and find a proper training data. Then you can test on our code or even propose your further method

**Comment by penincillin** [comment]
One of my colleagues tried our algorithm on pitch angle and gains performance enhancement.
