### ISSUE TITLE
what's meaning of pretrained model?

### ISSUE THREAD

**Issue by minushuang** [penincillin/DREAM#18]
this source  provides some pretrained models(4), named as cfp... ijba..., 
what's meaning of this name style?
Dose that mean cfp...model can only use to evaluate the CFP face data?
Or the model is trained on the CFP?

**Comment by penincillin** [comment]
cfp..model means use this pretrained model, you could get the same or similar results on CFP dataset we report in our paper.  cfp..model and ijba..model has similar architecture (both ResNet). The main differences is that they are trained with different data, so their performance might differ.

**Comment by jolinlinlin** [comment]
@penincillin hi,as you say,cfp..model and ijba..model are trained with different data.Can you tell me which dataset you used to train they?
