### ISSUE TITLE
How to generate the yaw angle of a face image in radian units, i.e. y in you paper?

### ISSUE THREAD

**Issue by ly-atdawn** [penincillin/DREAM#2]
The process of calculating  yaw angle of a face image in radian units as following:
![1](https://user-images.githubusercontent.com/23294606/38536061-9eab99d2-3cb9-11e8-8147-4b2fca79830a.png)
Could you share your codes for these processes? Thanks.

**Comment by penincillin** [comment]
Well, I am sorry that I couldn't share the code for you, since the code is part of the commercial project.
I provide an executable file in src/processing to calculate yaw angle.  You could follow that part of the readme to use that executable file.

**Comment by ly-atdawn** [comment]
ok. thanks

**Comment by slegall56** [comment]
In the paper, yaw coefficient is calculated as Y(x) = σ(4/Pi - 1). The paper said also that Y(x) should be equal to 0 for frontal face (for yaw = 0 I suppose)  which is not true with the sigmoid function. Furthermore, how do you deal with left and right yaw angle as Y(x) is between 0 and 1 according to the paper

**Comment by xiaoxingzeng** [comment]
@slegall56 , I suppose the "a sigmoid" function is 1/(1+e^-xb), b is a  positive integer number>1.

**Comment by penincillin** [comment]
@slegall56 @xiaoxingzeng  Actually, you could find the implementation of yaw angle transformation in .src/stitching/branch_util.py

**Comment by xiaoxingzeng** [comment]
@penincillin ,Thanks very much.

**Comment by tataganesh95** [comment]
@penincillin On which platform/OS does the executable for computing yaw angle run? And what command line arguments are to be passed to it?
