### ISSUE TITLE
How to get the 'yaw' information?

### ISSUE THREAD

**Issue by XiaoningLiu123** [penincillin/DREAM#20]
Hi, after review your code, I find yaw information is very important. And it is one of the branch of DREAM block, ringht？ So where is the code generate the yaw information in train/val label data, how can I get the yaw information on my own dataset? Thanks

**Comment by penincillin** [comment]
In /src/preprocess, we offer the python code and executable binary file for preprocessing the raw image and calculating the yaw angle. This code processes the images from CFP dataset. You could modify it and apply it on your own data.
