### ISSUE TITLE
inference & input/output question

### ISSUE THREAD

**Issue by guoxiaolu** [penincillin/DREAM#21]
I have read your paper but still have some questions:
1. inference code? there are only two evaluation codes in your project
2. the input is image data and yaw value, the output is new embedding, but how to remapping it to frontal face visually.
3. Is it possible to implement in large scale, not the interesting result in your paper? only sample dataset is given
Thank you very much, I think the module is similar as the classical STN network, Good job~

**Comment by zhengrongsheng** [comment]
@guoxiaolu  
Hello! I am also inteststed in this work,  and i want to ask some questions about this paper. BTW, this is my email: 2310798020@qq.com.  I look forward to getting in touch with you. Thank you!

**Comment by penincillin** [comment]
Thanks for asking.
1. Inference is quite simple, you just need to forward the face images through the trained model, and use the output feature for face verification or identification.
2. For visualization, please refer to this repo #11 
3. "implement in large scale" means implement our algorithm on large dataset? Actually, experiment results reported in our paper are all implemented on large scale dataset. But those datasets we used, such as MsCeleb-1M belong to sensetime and I have no right to make them public available. So I only release a sample dataset to make sure you could go through the whole pipeline successfully and have a rough idea of how the training data should be organized.

**Comment by guoxiaolu** [comment]
okay, Thank you, Good job~
