### ISSUE TITLE
what's the yaw type?

### ISSUE THREAD

**Issue by tjusxh** [penincillin/DREAM#22]
Thanks for your sharing. I found that there are two yaw types "nonli" and "linear" in the ijba dataset. Please what's the meaning? Thanks very much.

**Comment by penincillin** [comment]
The yaw angle lies in [-pi/2, pi/2] original. In DREAM block, yaw angle was mapped into [0, 1].
'linear' and 'nonli' means the mapping is in linear or non-linear manner.  More details could be found in the paper. You could search in the paper with the keywords "monotonous nonlinear mapping".
