### ISSUE TITLE
Why not apply latest face recognition loss function?

### ISSUE THREAD

**Issue by Joker316701882** [penincillin/DREAM#27]
@penincillin 
I noticed that in your source code, face recognition is treated as plain image classification task, without applying some latest loss function specifically designed for face recognition. For example, cosface loss    or arcloss. Have you tried that?

(In latest face recognition loss function, features and weights of last fc both need to be normalized, is it because normalized feature will hurt the performance in your pose robust algorithm?)

Thank you : )

**Comment by penincillin** [comment]
Thanks for asking,
the DREAM block is compatible with any face recognition loss, you could try them.
