### ISSUE TITLE
Problem about stitching/branch_train.py. 

### ISSUE THREAD

**Issue by SpiritBear000** [penincillin/DREAM#33]
At [https://github.com/penincillin/DREAM/blob/7bea01e5b108546a2b3a809ad17cf478607c9db5/src/stitching/branch_train.py#L52]

when i run this code, i get this error:

Traceback (most recent call last):
  File "/media/lab210/Work/WH_HOME/SubjectDownload/Project/Face-reid/[ DREAM-Face ]/DREAM/src/stitching/branch_train.py", line 134, in <module>
    main()
  File "/media/lab210/Work/WH_HOME/SubjectDownload/Project/Face-reid/[ DREAM-Face ]/DREAM/src/stitching/branch_train.py", line 52, in main
    losses.update(loss.data[0], loss.size(0))
RuntimeError: dimension specified as 0 but tensor has no dimensions

when i replace 'loss' to 'loss.size(0)'. the code can run. is it a bug when you design your code?

**Comment by tataganesh95** [comment]
Could be because of this - https://github.com/hunkim/PyTorchZeroToAll/issues/24

**Comment by SpiritBear000** [comment]
> Could be because of this - [hunkim/PyTorchZeroToAll#24](https://github.com/hunkim/PyTorchZeroToAll/issues/24)

thank you! There is another question to ask. 

In https://github.com/penincillin/DREAM/blob/7bea01e5b108546a2b3a809ad17cf478607c9db5/src/stitching/branch_train.py#L51
The output of MSEloss is a scalar，why a scalar have '.size()'?

And i am confused about the function 'AverageMeter' which is in (https://github.com/penincillin/DREAM/blob/7bea01e5b108546a2b3a809ad17cf478607c9db5/src/stitching/branch_train.py#L118)
what's the meaning of 'n' in  AverageMeter.update?

**Comment by penincillin** [comment]
Thanks for asking,
This issue might be caused by the version of Pytorch.
This code is developed with Pytorch 0.3 and might be not compatible with Pytorch 0.4. 
As for the bug you report, I believe it is not a tough one, you could try to solve by yourself :)

**Comment by clhne** [comment]
@SpiritBear000 
Just modify the code: 
losses.update(loss.data[0], loss.size(0))
to 
losses.update(loss.data, loss)
Then run it.
