### ISSUE TITLE
Are the given pretrained models derived from 'end2end' training or 'end2end + retrain' training?

### ISSUE THREAD

**Issue by aman-captech** [penincillin/DREAM#34]
Are the pretrained models: cfp_res50_end2end and ijba_res18_end2end- just trained end2end or is the DREAM block retrained after end2end training?

**Comment by penincillin** [comment]
Both of the models come from end2end training

**Comment by aman-captech** [comment]
The novelty of the paper lies in the fact that the DREAM block is retrained on profile-frontal face pairs for pose robust face recognition. Is there any specific reason why you have not provided the retrained model and if possible can you provide it as it would be very helpful for a college project I am working on?

Thanks!

**Comment by jolinlinlin** [comment]
@penincillin The given models all come from end2end training.But you said "The strategy ‘end2end+retrain’ gives the best performance over all." So can you provide the retrained model or tell me how to retrain the DREAM block after end2end training? I can't find retrain code in your public code.Thank you very much!
