### ISSUE TITLE
Prepare the feature extracted from any face recognition model (You could use the pretrained model we prepared).

### ISSUE THREAD

**Issue by jilner** [penincillin/DREAM#35]
hello 
         I  have download the pretrained model  from baiduyun，there are four moedls ,cfp_res50_end2end.pth  cfp_res50_naive.pth     ijba_res18_end2end.pth   ijba_res18_naive.pth,
I cant find  the  face recognition model  you   mentioned    ，could  you  release  the  model   ？
                                                                  thank  you verymuch

**Comment by penincillin** [comment]
Those four models you've downloaded are all face recognition model. You could use any one of them.
