### ISSUE TITLE
How to get frontal_list_nonli.txt in eval_cfp.py? What are the means of  last three values in estimate_pose.txt?

### ISSUE THREAD

**Issue by LaviLiu** [penincillin/DREAM#36]
Thank you for your code. I have some problems when I read the code:
1. I canot find frontal_list_nonli.txt and profile_list_nonli.txt which are used in eval_cfp.py. I want to know how to generate them?
2. I can get estimate_pose.txt by running. The items in estimate_pose.txt are like follows:
../../data/CFP/data/50_Cent/frontal/01.jpg 23.3769 1.43566 178.145 
../../data/CFP/data/50_Cent/frontal/02.jpg -7.93511 1.74187 -4.55453 
I want to know the means of the last three values.

**Comment by jnulzl** [comment]
@Laviyy For 1 , see readme "unzip CFP_protocol.zip" and then you can get it!
For 2, i guess three values are pitch,yaw,roll respectively.

**Comment by LaviLiu** [comment]
@jnulzl Thank you very much. I have got the  frontal_list_nonli.txt, but I still have other problems. Do you know how to transform linear yaw in estimate_pose.txt to nonlinear yaw in  frontal_list_nonli.txt and profile_list_nonli.txt. Are the following steps correct？
1. Transform the yaw in estimate_pose.txt to radian unit.
2. Input the radian yaw to σ(4/pi*radian_yaw -1) will get nonlinear yaw.

**Comment by jnulzl** [comment]
I guess you are  right,refer to "src/stitching/branch_util.py"
```python
def sigmoid(x):
    return 1 / (1 + math.exp(-x))

def norm_angle(angle):
    norm_angle = sigmoid(10 * (abs(angle) / 45.0 - 1))
    return norm_angle
```

**Comment by LaviLiu** [comment]
@jnulzl Thank you, I found the code.
