### ISSUE TITLE
Question about data processing on training set

### ISSUE THREAD

**Issue by PlumedSerpent** [penincillin/DREAM#37]
Hi, now I have gotten a pre-trained  model on our own dataset, if i want to apply DREAM block on it and the third training strategy in your paper, then I should do as below, right ?
step 1、Generate a celebrity_name_list file and then image_list.txt
step 2、Use the executable file you provide to get the yaw information of each image.
step 3、Add DREAM block to our model, then finetune our new-model （training both DREAM block and normal CNN part).
step 4、Continue  training the DREAM block separately with frontal-profile face pairs.

If I am right, how can I get the  frontal-profile face pairs in step 4 ?

**Comment by penincillin** [comment]
You need to pick up frontal-profile face pairs from the dataset you are using. The threshold to distinguish frontal and profile could be determined by yourself.
