### ISSUE TITLE
How to calculate yaw? Use equation in your paper can't get same result in IJBA

### ISSUE THREAD

**Issue by mwy691222563** [penincillin/DREAM#38]

**Comment by mwy691222563** [comment]
According to the equation in your paper,  yaw value belongs to [4*e^-5, 0.9998] when the angle belongs to [0, 90]. But in IJBA nonlinear_list.txt some yaw around e^-9.  How to get these values? 
Thank you

**Comment by penincillin** [comment]
Please use the function [norm_angle](https://github.com/penincillin/DREAM/blob/7bea01e5b108546a2b3a809ad17cf478607c9db5/src/stitching/branch_util.py#L10) to calculate yaw angles. Thanks
