### ISSUE TITLE
Couldn't find 'frontal_feat_naive.bin' and 'profile_feat_naive.bin' files

### ISSUE THREAD

**Issue by iamzhangyunlu** [penincillin/DREAM#41]
When run branch_test.py, it appears FileNotFoundError: [Errno 2] No such file or directory: '/home/sensetime/Downloads/ext_feat/data/frontal_feat_naive.bin'

**Comment by penincillin** [comment]
You need to prepare the extracted features and change the path to the path of your own feature

**Comment by iamzhangyunlu** [comment]
> You need to prepare the extracted features and change the path to the path of your own feature

so, these feature files need to be generated by me?

**Comment by iamzhangyunlu** [comment]
> You need to prepare the extracted features and change the path to the path of your own feature

So I need to generate these feature files by myself, right?

**Comment by penincillin** [comment]
Yes, you can generate these feature use any model you like.

**Comment by iamzhangyunlu** [comment]
> Yes, you can generate these feature use any model you like.

ok, thank you
