### ISSUE TITLE
I didn't find the executable binary file for calculating the yaw angle. Please help.

### ISSUE THREAD

**Issue by Rongchangle** [penincillin/DREAM#42]
![O~PGH(H}R
WFS2X_22YMP6](https://user-images.githubusercontent.com/25027202/60159920-d6b6e380-9826-11e9-8364-ca26825c8ca1.png)
![U7JU98~O LYO1JY6 TDZ2J](https://user-images.githubusercontent.com/25027202/60159984-f9e19300-9826-11e9-9b2e-d55bb63f8afb.png)

However, I didn't find this binary file in ‘’src/preprocess''.
If anyone find the binary file for calculating the yaw. Please help.

**Comment by penincillin** [comment]
test_process_align is the binary executable file.
