### ISSUE TITLE
How to use aligned face( 178x218) to extract feature?

### ISSUE THREAD

**Issue by DCore-2046** [penincillin/DREAM#48]
Thank you for sharing code. 
Q1: , how to extract feature using the released 178x218 cropped face? That is, how to transfer 178x218 to 224x224?
Thanks.

**Comment by penincillin** [comment]
Thanks for your interest in our work.
You can try to further crop the 178x218 to 178x178 or say 178x190, just make sure the aspect ratio is as close to 1.0 as possible. Then resize the cropped images to 224 x 224.
You can also try to pad the original 178x218 images to 224x224. You can have a background image, say all white or black, with size 224x224, then place your 178x218 image into the centers of background images.
I have no idea which method will have better performance. You can have a try by yourself.
