### ISSUE TITLE
Images with yaw between 21 and 49 degrees are not used for training the DREAM block

### ISSUE THREAD

**Issue by ksachdeva** [penincillin/DREAM#49]
Hi,

Thanks for this great work. I was looking at your stitching based training method and notice how you are building the inputs and targets.  

https://github.com/penincillin/DREAM/blob/7bea01e5b108546a2b3a809ad17cf478607c9db5/src/stitching/branch_train.py#L77

If I understood correctly, you are considering images with less or equal to 20 degree yaw to be frontal images. These images or rather the mean of the feature vectors of these images become your target/label. 

You consider the images with greater than 50 degree yaw to be the profile images and they become your inputs to the DREAM block along with the yaw.

Is there is any specific reason you are ignoring the images that are between 21 and 49 degrees ?. They are neither considered as inputs nor as labels/targets.

Regards & thanks
Kapil

**Comment by kaidic** [comment]
They are not used in training.
In testing, we regard faces between 21 and 49 as frontal faces as their performance is good enough and doesn't need further fixing.

**Comment by penincillin** [comment]
Thanks Kaidi for his reply.
According to my understanding, the faces whose yaw are larger than 20 and less than 50 is either not frontal and not profile. So we didn't use them in training.
20 and 50 are just two hyper-parameters / threshold we choose, you can also choose other two numbers and conduct experiments to check which group of threshold is better.

**Comment by ksachdeva** [comment]
Thanks @penincillin and @kaidic  for getting back on this and with clarifications.
