### ISSUE TITLE
Errors when calling test_process_align?

### ISSUE THREAD

**Issue by ly-atdawn** [penincillin/DREAM#5]
Hello, there are some problems when calling test_process_align:
1. In cfp_alignment.txt, every image has 21 pairs points,  which facial landmarks points you ysed? And, how to get these points??
2. pnp.txt, hoe to get this txt file?
3. When calling ./test_process_align $pnp_file $image_prefix $alignment_file $aligned_img_file $pose_file, I have a problem like this:
```
Data/Images/001/frontal/01.jpg ../../data/CFP/data/50_Cent/frontal/01.jpg
OpenCV Error: Assertion failed (_src.total() > 0) in warpPerspective, file /home/ly/git/DREAM/opencv-3.4.0/modules/imgproc/src/imgwarp.cpp, line 2978
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/ly/git/DREAM/opencv-3.4.0/modules/imgproc/src/imgwarp.cpp:2978: error: (-215) _src.total() > 0 in function warpPerspective

./align_cfp.sh: 行 16: 10665 已放弃               (核心已转储)./test_process_align $pnp_file $image_prefix $alignment_file $aligned_img_file $pose_file
```
How to solve this?? 
Thanks

**Comment by penincillin** [comment]
Thanks for your interest in our work. For your puzzles
1. For definition of the 21 facial landmarks, please follow the paper  "S. Zhu, C. Li, C. C. Loy, and X. Tang. Unconstrained face alignment via cascaded compositional learning. In CVPR, 2016."  Since the author of the paper hasn't made its code public available, you could use any other implementation as long as the order of the generated landmarks is consistent with the definition in the paper.
2. You could directly use the pnp.txt
3. For the third problem, could you offer more specific information? Such as on which operation system, you run this code.

**Comment by ly-atdawn** [comment]
Thanks a lot.
Thew info of operation system as following:
```
LSB Version:	n/a
Distributor ID:	openSUSE project
Description:	openSUSE Leap 42.3
Release:	42.3
Codename:	n/a

Linux KKofficeDesk58 4.4.92-31-default #1 SMP Sun Oct 22 06:56:24 UTC 2017 (1d80e8a) x86_64 x86_64 x86_64 GNU/Linux
```
And, the version of OpenCV is 3.4.0. The structure of CFP datasets as following:
```
the test_process_align file is in the current directory.
../../data/CFP
---------Data
-------------Fiducials
-------------Images
---------data
-------------50_Cent(each peoples' aligned face)
```
Any other infos??
Thanks again.

**Comment by penincillin** [comment]
First of all, please check the path of your input images of CFP dataset.
The operation system I use is Ubuntu 14.04, gcc version is 4.8.4. and version of opencv is 2.4

**Comment by LaviLiu** [comment]
@ly-atdawn Hello, I have the same problem with you. Have you resolved it?

**Comment by jolinlinlin** [comment]
@ly-atdawn @penincillin hello, I can't understand the effect and meaning of pnp.txt, and wha are meaning of the last three float number in every line of estimate_pose.txt .Can you tell me something details about these two files?I would appreciate it.

**Comment by lyatdawn** [comment]
@Laviyy No, I do use the author's codes to evaluate the yaw of images, I use the idea from: https://www.learnopencv.com/?s=headpose

**Comment by jolinlinlin** [comment]
@lyatdawn I read the page you have mentioned and I find when I use opencv and dlib to detect 68 landmarks, if the num of detected face using dlib is 0, I can't get landmarks and calculate yaw angel. Can you tell me how to solve this problem?Thank you very much!

**Comment by ghost** [comment]
@lyatdawn Hi, I have the same error with you, and I also change the method by using dlib and opencv to calculate the yaws, but have you found that this method could only calculate yaws ranging from -75 to 75, but can't estimate large yaws. how do you solve this problem? Thank you so much!

**Comment by peach1995** [comment]
You need to check the size of the image.Maybe your variable(image) is None.
