### ISSUE TITLE
How to estimate the yaw from a face image?

### ISSUE THREAD

**Issue by IrvingMeng** [penincillin/DREAM#50]
Hi, 

Thanks for the great work. May I ask which method do you use to get the yaw information?

**Comment by penincillin** [comment]
Please refer to this issue: https://github.com/penincillin/DREAM/issues/20#issuecomment-402940608

**Comment by IrvingMeng** [comment]
> Please refer to this issue: [#20 (comment)](https://github.com/penincillin/DREAM/issues/20#issuecomment-402940608)

Thanks so much!
