### ISSUE TITLE
test_process_align output

### ISSUE THREAD

**Issue by kgkevinwg** [penincillin/DREAM#52]
Hello @penincillin, thank you for your great work!
As I'm trying to reproduce the paper output, I've used the "test_process_align" file you provided to make pose prediction on CFP dataset. the binary file produced pose_file with the following format:

> "dir" "numberA" "numberB" "numberC"

I suppose that the numberA/B/C are yaw roll and pitch values, but in what order?  From the pose_file output,I can infer that numberB is the yaw value, but what's numberA/C actually belongs to? Looking forward your reply, Thanks!

**Comment by penincillin** [comment]
@kgkevinwg numberB should be yaw which is used in our paper. Actually, to reproduce the paper output, you can follow the instructions in the readme.

**Comment by mdja** [comment]
Hi penincillin,

interesting works. I want to ask what procedure you use to align input images? You only provide binary code for alignment. Since I have my own dataset that I want to align them for preprocessing.

**Comment by WinTsai** [comment]
Hi Penincilin,
I also want to know which 21 feature points on face to align the person's head position?
