### ISSUE TITLE
How to visualize the aligned face

### ISSUE THREAD

**Issue by LeeBC2298** [penincillin/DREAM#56]
![DreamVisualize](https://user-images.githubusercontent.com/41717225/90886423-ec04af00-e3e4-11ea-9254-0a2c4857f495.jpg)
I see this picture in your paper. Could you please tell me how to get the visualization result from the feature map?
Thank you.

**Comment by penincillin** [comment]
Please refer to this [issue](https://github.com/penincillin/DREAM/issues/11)

**Comment by LeeBC2298** [comment]
Thanks！
