### ISSUE TITLE
Regarding the functionality of test_process_align

### ISSUE THREAD

**Issue by ic-gcp** [penincillin/DREAM#57]
Hey @penincillin , Really appreciate the work and the effort you put behind this work. I had a few queries.

What exactly is the functionality of the binary file 'test_process_align'? What is it supposed to do and what is the output supposed to be? I don't need exact codes as I understand that they belong to sensetime, I only need a general understanding of what goes in and what comes out, so that I can figure out the process on my own.

Thanks

**Comment by penincillin** [comment]
Hi ic-gcp,

The first functionality of test_process_align is to generated aligned the face images as shown in [here](https://github.com/penincillin/DREAM/tree/master/image/align_sample). The second functionality is to predict yaw angles which is used in training DREAM block. 
I suggest you to try any convenient tools that can achieve these two functionalities.
Hope this can help you.

**Comment by ic-gcp** [comment]
@penincillin yes that was helpful, however we downloaded the subset of the MSCeleb dataset mentioned in the repo. In the labels txt file there are two values, one I assume is the image class and the other the yaw value to be added. When comparing the yaw values included with the images they dont make any sense. Which leads to the assumption that those values aren't exactly yaw values. Can you please help me understand what the values represent?
I've added the test labels and list file to help you understand the question better.

Thanks

[test_list.txt](https://github.com/penincillin/DREAM/files/5304018/test_list.txt)
[test_label.txt](https://github.com/penincillin/DREAM/files/5304019/test_label.txt)

**Comment by penincillin** [comment]
@ic-gcp 
Yes you are right, the values are original yaw angle (in angle representation) mapped with this [function](https://github.com/penincillin/DREAM/blob/7bea01e5b108546a2b3a809ad17cf478607c9db5/src/stitching/branch_util.py#L10)

**Comment by shivaang12** [comment]
Just wondering if you can share the source code for test_process_align binary.

Thanks
