### ISSUE TITLE
Error when running sh align_cfp.sh

### ISSUE THREAD

**Issue by WW2401** [penincillin/DREAM#58]
@penincillin Hi, when I ran sh align_cfp.sh I met the following problem, do you know the reason? thanks.
![image](https://user-images.githubusercontent.com/56579909/96357191-12b43d00-112b-11eb-8d29-2f8cf71a2496.png)

**Comment by penincillin** [comment]
This error is related to the path. Please change the path "/mnt/SSD/rongyu..." to the path of cfp dataset on your machine
