### ISSUE TITLE
frontal face generate!

### ISSUE THREAD

**Issue by diggle1** [penincillin/DREAM#59]
Hi, in your paper, you used the GAN model in ppgn[1] to map the deep features back to reconstructed images. Can you tell me whether the GAN model need to be trained with your feature? Or you directly used the model the author provide in the [page](https://github.com/Evolving-AI-Lab/ppgn)! And Which file you used to generate the face?

Looking forward to your reply！

[1]A. Nguyen, J. Yosinski, Y. Bengio, A. Dosovitskiy, and J. Clune. Plug & play generative networks: Conditional iterative generation of images in latent space. In CVPR, 2017.

**Comment by penincillin** [comment]
Please refer to this issue: https://github.com/penincillin/DREAM/issues/11

**Comment by diggle1** [comment]
okay, thank you very much
