### ISSUE TITLE
How to get the 3D facial landmarks coordinate?

### ISSUE THREAD

**Issue by ly-atdawn** [penincillin/DREAM#6]
Thanks for you answers all the time. My another question is:
If we have gettd the 2D facial landmarks coordinates, how to get the 3D facial landmarks coordinate?
Could you give me some references for detials? Or some codes? Thanks again

**Comment by penincillin** [comment]
I am a little puzzled about your question.
We only use 2D facial landmarks in our work.

**Comment by penincillin** [comment]
Well, in most part of our work, the 3D facial landmarks are not utilized.
They might only be useful in the process of calculating yaw angle.
For yaw angle calculating, you could refer to this [paper](https://www.cv-foundation.org/openaccess/content_cvpr_2015/papers/Zhang_Appearance-Based_Gaze_Estimation_2015_CVPR_paper.pdf). 
Actually, you could use any code which could calculate yaw angle given a single 2D face image.

**Comment by KangolHsu** [comment]
@ly-atdawn 
did you use the method in the URL below？
https://www.learnopencv.com/head-pose-estimation-using-opencv-and-dlib/

**Comment by ly-atdawn** [comment]
@KangolHsu Yes, I use this code to calculate the angle.
