### ISSUE TITLE
Source for test_process_align binary

### ISSUE THREAD

**Issue by shivaang12** [penincillin/DREAM#60]
It would be very helpful if you can share the source code for the test_process_align binary. Because the binary is looking for opencv 3.4 related shared object files which is a bit old. If you can share the source I can make it work with the new version of opencv too.

Thanks in advance.

**Comment by penincillin** [comment]
Source code of ``test_process_align`` belongs to a commercial company (i.e. [SenseTime](https://www.sensetime.com/)), thus it's not shareable. 
I would suggest you to try other open-source face alignment code, it is not necessary to use our original code, which is written in 2017 and out-of-date.
