### ISSUE TITLE
test_process_align file error

### ISSUE THREAD

**Issue by ekantbagri** [penincillin/DREAM#62]
so, when i try to run test_process_align file in align_cfp.sh, it says permission denied.

**Comment by ekantbagri** [comment]
i tried using chmod 755, worked but now it shows this error: 'error while loading shared libraries: libopencv_calib3d.so.3.4: cannot open shared object file: No such file or directory'

**Comment by penincillin** [comment]
@ekantbagri 
Sorry for the delayed reply. As the code might be out of date. I suggest you try the latest face-alignment code, such as [this one](https://github.com/1adrianb/face-alignment).
