### ISSUE TITLE
what is your Align protocol ？

### ISSUE THREAD

**Issue by KangolHsu** [penincillin/DREAM#7]
1.you said All the face images should be aligned. Please follow the align protocol in dataset CelebA.
what is your align protocol ？
2.CFP dataset only have 30 landmark ground truth, which is half face .how can we align face by this incomplete landmark ?
thanks for you reply.

**Comment by xisi789** [comment]
您好，我想问一下您找到CelebA 的 align protocol了吗？我想测试一下自己的图片，是不是也得先按照这个方法裁剪一下图片呢？

**Comment by Joker316701882** [comment]
@xisi789 @KangolHsu 
人脸是对称的，可以通过左眼中心和眉心推断出有眼中心的大致位置

**Comment by jolinlinlin** [comment]
@KangolHsu  hello,I'm finding align protocol of CelebA dataset. Can you tell me what it is if you have found it?Thank you very much!

**Comment by jolinlinlin** [comment]
@xisi789 你好，请问你找到CelebA 的 align protocol了吗？
