### ISSUE TITLE
stitching.zip ？

### ISSUE THREAD

**Issue by KangolHsu** [penincillin/DREAM#8]
where is the stitching.zip ？how can i get it？

**Comment by KangolHsu** [comment]
parser.add_argument('-ilf', '--image-list-file', default='../../data/stitching/sample_img_list.txt',
parser.add_argument('-ff', '--feat-file', default='../../data/stitching/ext_feat.bin',

You mean we should prepare sample_img_list.txt and corresponding ext_feat.bin extracted by pretrained model？

**Comment by penincillin** [comment]
Stitching.zip could be donwloaded either from [google drive] (https://drive.google.com/file/d/1x1K8MxAnVtpfaN3DfO4bdcKH39mmplj-/view) or [Baidu Yun](https://pan.baidu.com/s/1QIEeE9RxRY6iK3wCpvUh2Q)

**Comment by penincillin** [comment]
stitching.zip could either be downloaded from [Baidu Yun](https://pan.baidu.com/s/1QIEeE9RxRY6iK3wCpvUh2Q) or [Google Drive](https://drive.google.com/file/d/1x1K8MxAnVtpfaN3DfO4bdcKH39mmplj-/view)
