### ISSUE TITLE
what is the supported version of pytorch for this project?  

### ISSUE THREAD

**Issue by SpiritBear000** [penincillin/DREAM#9]
what is the supported version of pytorch for this project?

**Comment by penincillin** [comment]
Pytorch 0.3 will be fine and it is exactly the version we use.
You could also try Pytorch 0.4 (the latest version), I guess it will work well with a few modification.
In the end, remember to use Python 3 instead of Python 2

**Comment by SpiritBear000** [comment]
OK! thank you very much! @penincillin
